### ISSUE TITLE
Multiple message to sent

### ISSUE THREAD

**Issue by ChrysDaze** [xboxapi/Python-Wrapper#30]
Hi,

I'm doing an Xbox tournament into the PUBG Game.
I would like to send the result of a game to each user.

So i need to send multiple messages to many users ( 60 to 90 players ).

The problem is, when i do that, i get errors :
- It doesn't work for the 2nd user, so i tried to increase timeout => It doesn't work as expected
- With the improvement of the timeout, i could send for 20 users only, but some aren't really sent ( and no error message ) and then stop.

Error Message I get :

Traceback (most recent call last):
  File "C:\Users\Tje\PycharmProjects\PUBGapi\venv\lib\site-packages\urllib3\connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\Tje\PycharmProjects\PUBGapi\venv\lib\site-packages\urllib3\connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "D:\Program Files\Python\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "D:\Program Files\Python\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "D:\Program Files\Python\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "D:\Program Files\Python\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "D:\Program Files\Python\lib\ssl.py", line 1002, in recv_into
    return self.read(nbytes, buffer)
  File "D:\Program Files\Python\lib\ssl.py", line 865, in read
    return self._sslobj.read(len, buffer)
  File "D:\Program Files\Python\lib\ssl.py", line 625, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Tje\PycharmProjects\PUBGapi\venv\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\Tje\PycharmProjects\PUBGapi\venv\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\Tje\PycharmProjects\PUBGapi\venv\lib\site-packages\urllib3\util\retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\Tje\PycharmProjects\PUBGapi\venv\lib\site-packages\urllib3\packages\six.py", line 686, in reraise
    raise value
  File "C:\Users\Tje\PycharmProjects\PUBGapi\venv\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\Tje\PycharmProjects\PUBGapi\venv\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Users\Tje\PycharmProjects\PUBGapi\venv\lib\site-packages\urllib3\connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='xboxapi.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Tje/PycharmProjects/PUBGapi/pubg_script.py", line 173, in <module>
    client.gamer(gamertag=tmm_result['GT']).send_message(message=str_to_send)
  File "C:\Users\Tje\PycharmProjects\PUBGapi\xboxapi\gamer.py", line 93, in send_message
    return self.client.api_post('messages', payload)
  File "C:\Users\Tje\PycharmProjects\PUBGapi\xboxapi\client.py", line 87, in api_post
    timeout=self.timeout)
  File "C:\Users\Tje\PycharmProjects\PUBGapi\venv\lib\site-packages\requests\api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\Tje\PycharmProjects\PUBGapi\venv\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Tje\PycharmProjects\PUBGapi\venv\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Tje\PycharmProjects\PUBGapi\venv\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Tje\PycharmProjects\PUBGapi\venv\lib\site-packages\requests\adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='xboxapi.com', port=443): Read timed out. (read timeout=10)

**Comment by ChrysDaze** [comment]
What should I do to send to 90 users and be sure that they have been sent ?


Thanks :)

**Comment by bbhxwl** [comment]
haha
