### ISSUE TITLE
API Keys do not work

### ISSUE THREAD

**Issue by mjlomeli** [xboxapi/Python-Wrapper#37]
I've used this program before many times, so I'm sure I'm following it correctly. Any ideas?

![image](https://user-images.githubusercontent.com/46548793/233743150-c10a9de7-7910-4ffd-bdc1-d78821ec26c5.png)

**Comment by mjlomeli** [comment]
![image](https://user-images.githubusercontent.com/46548793/233743334-226787ef-757a-43f0-a541-7c3a182207a5.png)

**Comment by djekl** [comment]
Just pushed an update to this. The API has changed since this was written. The changes should work, however please refer to the docs for more info - https://xapi.us/docs

**Comment by mjlomeli** [comment]
I'm still getting the error. are you on PyPi xapi version - 2.0.1 ?

Lets see, I have the live account registered
![image](https://github.com/xboxapi/Python-Wrapper/assets/46548793/f5ff9c1a-44fa-4ddb-af05-200d2d721515)


I created the API token

![image](https://github.com/xboxapi/Python-Wrapper/assets/46548793/0c13347b-798b-40c3-b259-efac0baaca75)



```python
client = Client(api_key='the api key')
client.calls_remaining()
```

> ERROR:xboxapi:XboxAPI error: (401) Unauthorized
> Traceback (most recent call last):
>   File "C:\Users\optimus\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\231.8109.197\plugins\python\helpers\pydev\pydevconsole.py", line 364, in runcode
>     coro = func()
>   File "<input>", line 1, in <module>
>   File "C:\Users\optimus\Desktop\Xbox-SDK\.venv\lib\site-packages\xboxapi\client.py", line 98, in calls_remaining
>     limit_headers['X-RateLimit-Reset'] = server_headers['X-RateLimit-Reset']
>   File "C:\Users\optimus\Desktop\Xbox-SDK\.venv\lib\site-packages\requests\structures.py", line 52, in __getitem__
>     return self._store[key.lower()][1]
> KeyError: 'x-ratelimit-reset'
